### ISSUE TITLE
bbmap gets stuck if fwd/rev read files don't match

### ISSUE THREAD

**Issue by epruesse** [HRGV/phyloFlash#6]
If -read1 and -read2 refer to non-matching files, bbmap responds with the below error, but does not terminate. Hence, pF does not terminate either.

```
Exception in thread "Thread-39" java.lang.AssertionError: 
There appear to be different numbers of reads in the paired input files.
The pairing may have been corrupted by an upstream process.  It may be fixable by running repair.sh.
	at stream.ConcurrentGenericReadInputStream.pair(ConcurrentGenericReadInputStream.java:492)
	at stream.ConcurrentGenericReadInputStream.readLists(ConcurrentGenericReadInputStream.java:358)
	at stream.ConcurrentGenericReadInputStream.run(ConcurrentGenericReadInputStream.java:195)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ebioman** [comment]
Hi no idea why that was closed ? I am having similar problem running bbmap in nextflow.
Essentially the pod/image will never be seen as failure as the exit code is not returned.
Any update on this ?
